import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import FooterPage from "../components/Footer";
import Navlinks from "../components/Navlinks";
import Marquee from "../components/Marquee";


const notoSerifBengali =Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin","bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Header ></Header>
           <Navlinks></Navlinks>
        <Marquee></Marquee>
     
   <main className="max-w-7xl  mx-auto">
     {children}
   </main>
   <FooterPage></FooterPage>
        
        
        </body>
    </html>
  );
}
